### ISSUE TITLE
Fail to compile caffe

### ISSUE THREAD

**Issue by yclai1114** [ShuangLI59/person_search#17]
Hi, I tried to compile the caffe but failed to generate the caffe.pb.cc.o
ubuntu@ubuntu-S2600CW:~/Downloads/person_search/caffe/build$ cmake .. -DUSE_MPI=ON -DCUDNN_INCLUDE=/usr/local/cuda-8.0/include -DCUDNN_LIBRARY=/usr/local/cuda-8.0/lib64/libcudnn.so
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   thread
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35 sm_21
-- Cuda + Boost 1.55: Applying noinline work around
-- OpenCV found (/usr/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.12.0 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1625-gaed3884
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.2.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.8)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35 sm_21
--   cuDNN             :   Yes
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.6)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--   NumPy             :   /usr/local/lib/python2.7/dist-packages/numpy/core/include (ver 1.12.0)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.6)
--   config_file       :   /home/ubuntu/Downloads/person_search/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home/ubuntu/Downloads/person_search/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Downloads/person_search/caffe/build

ubuntu@ubuntu-S2600CW:~/Downloads/person_search/caffe/build$ make -j8
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc: In member function ‘virtual bool caffe::BlobShape::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3066:24: error: expected ‘<’ before ‘<:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                        ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3066:24: error: expected type-specifier before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3066:24: error: expected ‘>’ before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3066:24: error: expected ‘(’ before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3066:26: error: expected identifier before ‘:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                          ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3067:58: error: expected ‘]’ before ‘{’ token
             static_cast<::google::protobuf::uint8>(10u)) {
                                                          ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:40:0,
                 from /home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.h:9,
                 from /home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:5:
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc: In lambda function:
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3070:18: error: ‘input’ is not captured
                  input, this->mutable_dim())));
                  ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3068:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
           ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3070:25: error: ‘this’ was not captured for this lambda function
                  input, this->mutable_dim())));
                         ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3068:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
           ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3056:68: error: label ‘failure’ used but not defined
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                                    ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3068:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
           ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc: In member function ‘virtual bool caffe::BlobShape::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3071:9: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
         } else if (static_cast<::google::protobuf::uint8>(tag) ==
         ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3071:11: error: expected ‘)’ before ‘else’
         } else if (static_cast<::google::protobuf::uint8>(tag) ==
           ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3071:11: error: expected ‘)’ before ‘else’
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc: In member function ‘virtual bool caffe::BlobProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3379:24: error: expected ‘<’ before ‘<:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                        ^
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3379:24: error: expected type-specifier before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3379:24: error: expected ‘>’ before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3379:24: error: expected ‘(’ before ‘<:’ token
/home/ubuntu/Downloads/person_search/caffe/build/include/caffe/proto/caffe.pb.cc:3379:26: error: expected identifier before ‘:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                          ^
make[2]: *** [src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/proto.dir/all] Error 2
make: *** [all] Error 2

Many thanks for help

**Comment by Cysu** [comment]
Could you please check the compiler version by

    g++ --version
    protoc --version

Mine is `g++ 4.8.4` and `libprotoc 2.6.1`.

**Comment by yclai1114** [comment]
ubuntu@ubuntu-S2600CW:~/Downloads/person_search/caffe/build$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ubuntu@ubuntu-S2600CW:~/Downloads/person_search/caffe/build$ protoc --version
libprotoc 3.2.0

**Comment by Cysu** [comment]
I think it should be fine to compile with `libprotoc 3.2.0`. Could you please remove the build directory with `rm -rf build` and recompile it?

**Comment by yclai1114** [comment]
problem solved after I installed the libprotoc 2.6.1

thank you
